// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.27.0

package roleData

import (
	"database/sql"
	"time"

	"github.com/google/uuid"
)

type Class struct {
	ID        uuid.UUID      `json:"id"`
	Name      string         `json:"name"`
	Subject   sql.NullString `json:"subject"`
	Grade     sql.NullString `json:"grade"`
	Code      string         `json:"code"`
	DeletedAt sql.NullTime   `json:"deleted_at"`
	CreatedAt time.Time      `json:"created_at"`
	UpdatedAt time.Time      `json:"updated_at"`
}

type Member struct {
	ID        uuid.UUID    `json:"id"`
	RoleID    uuid.UUID    `json:"role_id"`
	UserID    uuid.UUID    `json:"user_id"`
	ClassID   uuid.UUID    `json:"class_id"`
	DeletedAt sql.NullTime `json:"deleted_at"`
	CreatedAt time.Time    `json:"created_at"`
	UpdatedAt time.Time    `json:"updated_at"`
}

type Role struct {
	ID        uuid.UUID    `json:"id"`
	Key       string       `json:"key"`
	DeletedAt sql.NullTime `json:"deleted_at"`
	CreatedAt time.Time    `json:"created_at"`
	UpdatedAt time.Time    `json:"updated_at"`
}

type Unit struct {
	ID        uuid.UUID    `json:"id"`
	Name      string       `json:"name"`
	ClassID   uuid.UUID    `json:"class_id"`
	DeletedAt sql.NullTime `json:"deleted_at"`
	CreatedAt time.Time    `json:"created_at"`
	UpdatedAt time.Time    `json:"updated_at"`
}
