// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.27.0

package roleData

import (
	"context"

	"github.com/google/uuid"
)

type Querier interface {
	GetRole(ctx context.Context, id uuid.UUID) (GetRoleRow, error)
}

var _ Querier = (*Queries)(nil)
