// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.27.0

package roleData

import (
	"context"
)

type Querier interface {
	GetRoleByID(ctx context.Context, id string) (GetRoleByIDRow, error)
	GetRoleByKey(ctx context.Context, key string) (GetRoleByKeyRow, error)
}

var _ Querier = (*Queries)(nil)
