// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.27.0
// source: role.sql

package roleData

import (
	"context"

	"github.com/google/uuid"
)

const getRole = `-- name: GetRole :one
SELECT
  id,
  key
FROM roles
WHERE id = $1
AND deleted_at IS NULL
LIMIT 1
`

type GetRoleRow struct {
	ID  uuid.UUID `json:"id"`
	Key string    `json:"key"`
}

func (q *Queries) GetRole(ctx context.Context, id uuid.UUID) (GetRoleRow, error) {
	row := q.db.QueryRowContext(ctx, getRole, id)
	var i GetRoleRow
	err := row.Scan(&i.ID, &i.Key)
	return i, err
}
