version: '3.1'

services:

  sa_class_management_app:
    build:
      context: ../
      dockerfile: .dockers/Dockerfile
    container_name: sa_class_management_app
    environment:
      TZ: America/Hermosillo
    volumes:
      - ../:/usr/src/app
    ports:
      - 8003:8000
    depends_on:
      sa_class_management_db:
        condition: service_started
    networks:
      - saloncito
      - sa_class_management_network

  sa_class_management_db:
    image: postgres:15.2
    container_name: sa_class_management_db
    environment:
      POSTGRES_PASSWORD: example
      POSTGRES_DB: sa_class_management
      TZ: America/Hermosillo
    volumes:
      - ../DB/postgresql:/var/lib/postgresql/data
    ports:
      - 5435:5432
    healthcheck:
      test: [ "CMD-SHELL", "pg_isready -U postgres" ]
      interval: 10s
      timeout: 5s
      retries: 5
    networks:
      - sa_class_management_network

  sa_class_management_adminer:
    image: adminer
    container_name: sa_class_management_adminer
    environment:
      TZ: America/Hermosillo
      ADMINER_DESIGN: "ng9"
    ports:
      - 8083:8080
    depends_on:
      sa_class_management_db:
        condition: service_started
    networks:
      - sa_class_management_network

networks:
  saloncito:
    external: true
  sa_class_management_network:
    driver: bridge