// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.27.0
// source: class.sql

package classData

import (
	"context"
	"database/sql"
)

const getClass = `-- name: GetClass :one
SELECT
  id,
  name,
  subject,
  grade
FROM classes
WHERE id = $1
AND deleted_at IS NULL
LIMIT 1
`

type GetClassRow struct {
	ID      string         `json:"id"`
	Name    string         `json:"name"`
	Subject sql.NullString `json:"subject"`
	Grade   sql.NullString `json:"grade"`
}

func (q *Queries) GetClass(ctx context.Context, id string) (GetClassRow, error) {
	row := q.db.QueryRowContext(ctx, getClass, id)
	var i GetClassRow
	err := row.Scan(
		&i.ID,
		&i.Name,
		&i.Subject,
		&i.Grade,
	)
	return i, err
}
