// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.27.0

package classData

import (
	"context"
)

type Querier interface {
	CreateClass(ctx context.Context, arg CreateClassParams) (Class, error)
	GetClass(ctx context.Context, id string) (GetClassRow, error)
	ListClasses(ctx context.Context, arg ListClassesParams) ([]ListClassesRow, error)
}

var _ Querier = (*Queries)(nil)
