// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.27.0

package classData

import (
	"context"

	"github.com/google/uuid"
)

type Querier interface {
	GetClass(ctx context.Context, id uuid.UUID) (GetClassRow, error)
}

var _ Querier = (*Queries)(nil)
