// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.27.0

package unitData

import (
	"context"
)

type Querier interface {
	GetUnit(ctx context.Context, id string) (GetUnitRow, error)
}

var _ Querier = (*Queries)(nil)
