// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.27.0
// source: unit.sql

package unitData

import (
	"context"

	"github.com/google/uuid"
)

const getUnit = `-- name: GetUnit :one
SELECT
  id,
  name
FROM units
WHERE id = $1
AND deleted_at IS NULL
LIMIT 1
`

type GetUnitRow struct {
	ID   uuid.UUID `json:"id"`
	Name string    `json:"name"`
}

func (q *Queries) GetUnit(ctx context.Context, id uuid.UUID) (GetUnitRow, error) {
	row := q.db.QueryRowContext(ctx, getUnit, id)
	var i GetUnitRow
	err := row.Scan(&i.ID, &i.Name)
	return i, err
}
