// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.27.0

package classDb

import (
	"context"
)

type Querier interface {
	GetClass(ctx context.Context, id string) (GetClassRow, error)
}

var _ Querier = (*Queries)(nil)
