// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.35.2
// 	protoc        v3.21.12
// source: class.proto

package proto

import (
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	reflect "reflect"
	sync "sync"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

type ClassData struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	Id      string `protobuf:"bytes,1,opt,name=id,proto3" json:"id,omitempty"`
	Name    string `protobuf:"bytes,2,opt,name=name,proto3" json:"name,omitempty"`
	Subject string `protobuf:"bytes,3,opt,name=subject,proto3" json:"subject,omitempty"`
	Grade   string `protobuf:"bytes,4,opt,name=grade,proto3" json:"grade,omitempty"`
	Code    string `protobuf:"bytes,5,opt,name=code,proto3" json:"code,omitempty"`
}

func (x *ClassData) Reset() {
	*x = ClassData{}
	mi := &file_class_proto_msgTypes[0]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ClassData) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ClassData) ProtoMessage() {}

func (x *ClassData) ProtoReflect() protoreflect.Message {
	mi := &file_class_proto_msgTypes[0]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ClassData.ProtoReflect.Descriptor instead.
func (*ClassData) Descriptor() ([]byte, []int) {
	return file_class_proto_rawDescGZIP(), []int{0}
}

func (x *ClassData) GetId() string {
	if x != nil {
		return x.Id
	}
	return ""
}

func (x *ClassData) GetName() string {
	if x != nil {
		return x.Name
	}
	return ""
}

func (x *ClassData) GetSubject() string {
	if x != nil {
		return x.Subject
	}
	return ""
}

func (x *ClassData) GetGrade() string {
	if x != nil {
		return x.Grade
	}
	return ""
}

func (x *ClassData) GetCode() string {
	if x != nil {
		return x.Code
	}
	return ""
}

type ClassesWithMeta struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	Classes []*ClassData `protobuf:"bytes,1,rep,name=classes,proto3" json:"classes,omitempty"`
	Meta    *Meta        `protobuf:"bytes,2,opt,name=meta,proto3" json:"meta,omitempty"`
}

func (x *ClassesWithMeta) Reset() {
	*x = ClassesWithMeta{}
	mi := &file_class_proto_msgTypes[1]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ClassesWithMeta) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ClassesWithMeta) ProtoMessage() {}

func (x *ClassesWithMeta) ProtoReflect() protoreflect.Message {
	mi := &file_class_proto_msgTypes[1]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ClassesWithMeta.ProtoReflect.Descriptor instead.
func (*ClassesWithMeta) Descriptor() ([]byte, []int) {
	return file_class_proto_rawDescGZIP(), []int{1}
}

func (x *ClassesWithMeta) GetClasses() []*ClassData {
	if x != nil {
		return x.Classes
	}
	return nil
}

func (x *ClassesWithMeta) GetMeta() *Meta {
	if x != nil {
		return x.Meta
	}
	return nil
}

type CreateClassRequest struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	UserId  string `protobuf:"bytes,1,opt,name=userId,proto3" json:"userId,omitempty"`
	Name    string `protobuf:"bytes,2,opt,name=name,proto3" json:"name,omitempty"`
	Subject string `protobuf:"bytes,3,opt,name=subject,proto3" json:"subject,omitempty"`
	Grade   string `protobuf:"bytes,4,opt,name=grade,proto3" json:"grade,omitempty"`
}

func (x *CreateClassRequest) Reset() {
	*x = CreateClassRequest{}
	mi := &file_class_proto_msgTypes[2]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *CreateClassRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*CreateClassRequest) ProtoMessage() {}

func (x *CreateClassRequest) ProtoReflect() protoreflect.Message {
	mi := &file_class_proto_msgTypes[2]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use CreateClassRequest.ProtoReflect.Descriptor instead.
func (*CreateClassRequest) Descriptor() ([]byte, []int) {
	return file_class_proto_rawDescGZIP(), []int{2}
}

func (x *CreateClassRequest) GetUserId() string {
	if x != nil {
		return x.UserId
	}
	return ""
}

func (x *CreateClassRequest) GetName() string {
	if x != nil {
		return x.Name
	}
	return ""
}

func (x *CreateClassRequest) GetSubject() string {
	if x != nil {
		return x.Subject
	}
	return ""
}

func (x *CreateClassRequest) GetGrade() string {
	if x != nil {
		return x.Grade
	}
	return ""
}

type CreateClassResponse struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	// Types that are assignable to Result:
	//
	//	*CreateClassResponse_Class
	//	*CreateClassResponse_Error
	Result isCreateClassResponse_Result `protobuf_oneof:"result"`
}

func (x *CreateClassResponse) Reset() {
	*x = CreateClassResponse{}
	mi := &file_class_proto_msgTypes[3]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *CreateClassResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*CreateClassResponse) ProtoMessage() {}

func (x *CreateClassResponse) ProtoReflect() protoreflect.Message {
	mi := &file_class_proto_msgTypes[3]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use CreateClassResponse.ProtoReflect.Descriptor instead.
func (*CreateClassResponse) Descriptor() ([]byte, []int) {
	return file_class_proto_rawDescGZIP(), []int{3}
}

func (m *CreateClassResponse) GetResult() isCreateClassResponse_Result {
	if m != nil {
		return m.Result
	}
	return nil
}

func (x *CreateClassResponse) GetClass() *ClassData {
	if x, ok := x.GetResult().(*CreateClassResponse_Class); ok {
		return x.Class
	}
	return nil
}

func (x *CreateClassResponse) GetError() *Error {
	if x, ok := x.GetResult().(*CreateClassResponse_Error); ok {
		return x.Error
	}
	return nil
}

type isCreateClassResponse_Result interface {
	isCreateClassResponse_Result()
}

type CreateClassResponse_Class struct {
	Class *ClassData `protobuf:"bytes,1,opt,name=class,proto3,oneof"`
}

type CreateClassResponse_Error struct {
	Error *Error `protobuf:"bytes,2,opt,name=error,proto3,oneof"`
}

func (*CreateClassResponse_Class) isCreateClassResponse_Result() {}

func (*CreateClassResponse_Error) isCreateClassResponse_Result() {}

type JoinClassRequest struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	UserId string `protobuf:"bytes,1,opt,name=userId,proto3" json:"userId,omitempty"`
	Code   string `protobuf:"bytes,2,opt,name=code,proto3" json:"code,omitempty"`
}

func (x *JoinClassRequest) Reset() {
	*x = JoinClassRequest{}
	mi := &file_class_proto_msgTypes[4]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *JoinClassRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*JoinClassRequest) ProtoMessage() {}

func (x *JoinClassRequest) ProtoReflect() protoreflect.Message {
	mi := &file_class_proto_msgTypes[4]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use JoinClassRequest.ProtoReflect.Descriptor instead.
func (*JoinClassRequest) Descriptor() ([]byte, []int) {
	return file_class_proto_rawDescGZIP(), []int{4}
}

func (x *JoinClassRequest) GetUserId() string {
	if x != nil {
		return x.UserId
	}
	return ""
}

func (x *JoinClassRequest) GetCode() string {
	if x != nil {
		return x.Code
	}
	return ""
}

type JoinClassResponse struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	// Types that are assignable to Result:
	//
	//	*JoinClassResponse_Class
	//	*JoinClassResponse_Error
	Result isJoinClassResponse_Result `protobuf_oneof:"result"`
}

func (x *JoinClassResponse) Reset() {
	*x = JoinClassResponse{}
	mi := &file_class_proto_msgTypes[5]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *JoinClassResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*JoinClassResponse) ProtoMessage() {}

func (x *JoinClassResponse) ProtoReflect() protoreflect.Message {
	mi := &file_class_proto_msgTypes[5]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use JoinClassResponse.ProtoReflect.Descriptor instead.
func (*JoinClassResponse) Descriptor() ([]byte, []int) {
	return file_class_proto_rawDescGZIP(), []int{5}
}

func (m *JoinClassResponse) GetResult() isJoinClassResponse_Result {
	if m != nil {
		return m.Result
	}
	return nil
}

func (x *JoinClassResponse) GetClass() *ClassData {
	if x, ok := x.GetResult().(*JoinClassResponse_Class); ok {
		return x.Class
	}
	return nil
}

func (x *JoinClassResponse) GetError() *Error {
	if x, ok := x.GetResult().(*JoinClassResponse_Error); ok {
		return x.Error
	}
	return nil
}

type isJoinClassResponse_Result interface {
	isJoinClassResponse_Result()
}

type JoinClassResponse_Class struct {
	Class *ClassData `protobuf:"bytes,1,opt,name=class,proto3,oneof"`
}

type JoinClassResponse_Error struct {
	Error *Error `protobuf:"bytes,2,opt,name=error,proto3,oneof"`
}

func (*JoinClassResponse_Class) isJoinClassResponse_Result() {}

func (*JoinClassResponse_Error) isJoinClassResponse_Result() {}

type ListClassesRequest struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	UserId string `protobuf:"bytes,1,opt,name=userId,proto3" json:"userId,omitempty"`
	Page   int32  `protobuf:"varint,2,opt,name=page,proto3" json:"page,omitempty"`
	Limit  int32  `protobuf:"varint,3,opt,name=limit,proto3" json:"limit,omitempty"`
}

func (x *ListClassesRequest) Reset() {
	*x = ListClassesRequest{}
	mi := &file_class_proto_msgTypes[6]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ListClassesRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ListClassesRequest) ProtoMessage() {}

func (x *ListClassesRequest) ProtoReflect() protoreflect.Message {
	mi := &file_class_proto_msgTypes[6]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ListClassesRequest.ProtoReflect.Descriptor instead.
func (*ListClassesRequest) Descriptor() ([]byte, []int) {
	return file_class_proto_rawDescGZIP(), []int{6}
}

func (x *ListClassesRequest) GetUserId() string {
	if x != nil {
		return x.UserId
	}
	return ""
}

func (x *ListClassesRequest) GetPage() int32 {
	if x != nil {
		return x.Page
	}
	return 0
}

func (x *ListClassesRequest) GetLimit() int32 {
	if x != nil {
		return x.Limit
	}
	return 0
}

type ListClassesResponse struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	// Types that are assignable to Result:
	//
	//	*ListClassesResponse_Data
	//	*ListClassesResponse_Error
	Result isListClassesResponse_Result `protobuf_oneof:"result"`
}

func (x *ListClassesResponse) Reset() {
	*x = ListClassesResponse{}
	mi := &file_class_proto_msgTypes[7]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ListClassesResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ListClassesResponse) ProtoMessage() {}

func (x *ListClassesResponse) ProtoReflect() protoreflect.Message {
	mi := &file_class_proto_msgTypes[7]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ListClassesResponse.ProtoReflect.Descriptor instead.
func (*ListClassesResponse) Descriptor() ([]byte, []int) {
	return file_class_proto_rawDescGZIP(), []int{7}
}

func (m *ListClassesResponse) GetResult() isListClassesResponse_Result {
	if m != nil {
		return m.Result
	}
	return nil
}

func (x *ListClassesResponse) GetData() *ClassesWithMeta {
	if x, ok := x.GetResult().(*ListClassesResponse_Data); ok {
		return x.Data
	}
	return nil
}

func (x *ListClassesResponse) GetError() *Error {
	if x, ok := x.GetResult().(*ListClassesResponse_Error); ok {
		return x.Error
	}
	return nil
}

type isListClassesResponse_Result interface {
	isListClassesResponse_Result()
}

type ListClassesResponse_Data struct {
	Data *ClassesWithMeta `protobuf:"bytes,1,opt,name=data,proto3,oneof"`
}

type ListClassesResponse_Error struct {
	Error *Error `protobuf:"bytes,2,opt,name=error,proto3,oneof"`
}

func (*ListClassesResponse_Data) isListClassesResponse_Result() {}

func (*ListClassesResponse_Error) isListClassesResponse_Result() {}

type GetClassCodeRequest struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	UserId  string `protobuf:"bytes,1,opt,name=userId,proto3" json:"userId,omitempty"`
	ClassId string `protobuf:"bytes,2,opt,name=classId,proto3" json:"classId,omitempty"`
}

func (x *GetClassCodeRequest) Reset() {
	*x = GetClassCodeRequest{}
	mi := &file_class_proto_msgTypes[8]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *GetClassCodeRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*GetClassCodeRequest) ProtoMessage() {}

func (x *GetClassCodeRequest) ProtoReflect() protoreflect.Message {
	mi := &file_class_proto_msgTypes[8]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use GetClassCodeRequest.ProtoReflect.Descriptor instead.
func (*GetClassCodeRequest) Descriptor() ([]byte, []int) {
	return file_class_proto_rawDescGZIP(), []int{8}
}

func (x *GetClassCodeRequest) GetUserId() string {
	if x != nil {
		return x.UserId
	}
	return ""
}

func (x *GetClassCodeRequest) GetClassId() string {
	if x != nil {
		return x.ClassId
	}
	return ""
}

type GetClassCodeResponse struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	// Types that are assignable to Result:
	//
	//	*GetClassCodeResponse_Code
	//	*GetClassCodeResponse_Error
	Result isGetClassCodeResponse_Result `protobuf_oneof:"result"`
}

func (x *GetClassCodeResponse) Reset() {
	*x = GetClassCodeResponse{}
	mi := &file_class_proto_msgTypes[9]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *GetClassCodeResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*GetClassCodeResponse) ProtoMessage() {}

func (x *GetClassCodeResponse) ProtoReflect() protoreflect.Message {
	mi := &file_class_proto_msgTypes[9]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use GetClassCodeResponse.ProtoReflect.Descriptor instead.
func (*GetClassCodeResponse) Descriptor() ([]byte, []int) {
	return file_class_proto_rawDescGZIP(), []int{9}
}

func (m *GetClassCodeResponse) GetResult() isGetClassCodeResponse_Result {
	if m != nil {
		return m.Result
	}
	return nil
}

func (x *GetClassCodeResponse) GetCode() string {
	if x, ok := x.GetResult().(*GetClassCodeResponse_Code); ok {
		return x.Code
	}
	return ""
}

func (x *GetClassCodeResponse) GetError() *Error {
	if x, ok := x.GetResult().(*GetClassCodeResponse_Error); ok {
		return x.Error
	}
	return nil
}

type isGetClassCodeResponse_Result interface {
	isGetClassCodeResponse_Result()
}

type GetClassCodeResponse_Code struct {
	Code string `protobuf:"bytes,1,opt,name=code,proto3,oneof"`
}

type GetClassCodeResponse_Error struct {
	Error *Error `protobuf:"bytes,2,opt,name=error,proto3,oneof"`
}

func (*GetClassCodeResponse_Code) isGetClassCodeResponse_Result() {}

func (*GetClassCodeResponse_Error) isGetClassCodeResponse_Result() {}

var File_class_proto protoreflect.FileDescriptor

var file_class_proto_rawDesc = []byte{
	0x0a, 0x0b, 0x63, 0x6c, 0x61, 0x73, 0x73, 0x2e, 0x70, 0x72, 0x6f, 0x74, 0x6f, 0x12, 0x05, 0x63,
	0x6c, 0x61, 0x73, 0x73, 0x1a, 0x0c, 0x73, 0x68, 0x61, 0x72, 0x65, 0x64, 0x2e, 0x70, 0x72, 0x6f,
	0x74, 0x6f, 0x22, 0x73, 0x0a, 0x09, 0x43, 0x6c, 0x61, 0x73, 0x73, 0x44, 0x61, 0x74, 0x61, 0x12,
	0x0e, 0x0a, 0x02, 0x69, 0x64, 0x18, 0x01, 0x20, 0x01, 0x28, 0x09, 0x52, 0x02, 0x69, 0x64, 0x12,
	0x12, 0x0a, 0x04, 0x6e, 0x61, 0x6d, 0x65, 0x18, 0x02, 0x20, 0x01, 0x28, 0x09, 0x52, 0x04, 0x6e,
	0x61, 0x6d, 0x65, 0x12, 0x18, 0x0a, 0x07, 0x73, 0x75, 0x62, 0x6a, 0x65, 0x63, 0x74, 0x18, 0x03,
	0x20, 0x01, 0x28, 0x09, 0x52, 0x07, 0x73, 0x75, 0x62, 0x6a, 0x65, 0x63, 0x74, 0x12, 0x14, 0x0a,
	0x05, 0x67, 0x72, 0x61, 0x64, 0x65, 0x18, 0x04, 0x20, 0x01, 0x28, 0x09, 0x52, 0x05, 0x67, 0x72,
	0x61, 0x64, 0x65, 0x12, 0x12, 0x0a, 0x04, 0x63, 0x6f, 0x64, 0x65, 0x18, 0x05, 0x20, 0x01, 0x28,
	0x09, 0x52, 0x04, 0x63, 0x6f, 0x64, 0x65, 0x22, 0x5f, 0x0a, 0x0f, 0x43, 0x6c, 0x61, 0x73, 0x73,
	0x65, 0x73, 0x57, 0x69, 0x74, 0x68, 0x4d, 0x65, 0x74, 0x61, 0x12, 0x2a, 0x0a, 0x07, 0x63, 0x6c,
	0x61, 0x73, 0x73, 0x65, 0x73, 0x18, 0x01, 0x20, 0x03, 0x28, 0x0b, 0x32, 0x10, 0x2e, 0x63, 0x6c,
	0x61, 0x73, 0x73, 0x2e, 0x43, 0x6c, 0x61, 0x73, 0x73, 0x44, 0x61, 0x74, 0x61, 0x52, 0x07, 0x63,
	0x6c, 0x61, 0x73, 0x73, 0x65, 0x73, 0x12, 0x20, 0x0a, 0x04, 0x6d, 0x65, 0x74, 0x61, 0x18, 0x02,
	0x20, 0x01, 0x28, 0x0b, 0x32, 0x0c, 0x2e, 0x73, 0x68, 0x61, 0x72, 0x65, 0x64, 0x2e, 0x4d, 0x65,
	0x74, 0x61, 0x52, 0x04, 0x6d, 0x65, 0x74, 0x61, 0x22, 0x70, 0x0a, 0x12, 0x43, 0x72, 0x65, 0x61,
	0x74, 0x65, 0x43, 0x6c, 0x61, 0x73, 0x73, 0x52, 0x65, 0x71, 0x75, 0x65, 0x73, 0x74, 0x12, 0x16,
	0x0a, 0x06, 0x75, 0x73, 0x65, 0x72, 0x49, 0x64, 0x18, 0x01, 0x20, 0x01, 0x28, 0x09, 0x52, 0x06,
	0x75, 0x73, 0x65, 0x72, 0x49, 0x64, 0x12, 0x12, 0x0a, 0x04, 0x6e, 0x61, 0x6d, 0x65, 0x18, 0x02,
	0x20, 0x01, 0x28, 0x09, 0x52, 0x04, 0x6e, 0x61, 0x6d, 0x65, 0x12, 0x18, 0x0a, 0x07, 0x73, 0x75,
	0x62, 0x6a, 0x65, 0x63, 0x74, 0x18, 0x03, 0x20, 0x01, 0x28, 0x09, 0x52, 0x07, 0x73, 0x75, 0x62,
	0x6a, 0x65, 0x63, 0x74, 0x12, 0x14, 0x0a, 0x05, 0x67, 0x72, 0x61, 0x64, 0x65, 0x18, 0x04, 0x20,
	0x01, 0x28, 0x09, 0x52, 0x05, 0x67, 0x72, 0x61, 0x64, 0x65, 0x22, 0x70, 0x0a, 0x13, 0x43, 0x72,
	0x65, 0x61, 0x74, 0x65, 0x43, 0x6c, 0x61, 0x73, 0x73, 0x52, 0x65, 0x73, 0x70, 0x6f, 0x6e, 0x73,
	0x65, 0x12, 0x28, 0x0a, 0x05, 0x63, 0x6c, 0x61, 0x73, 0x73, 0x18, 0x01, 0x20, 0x01, 0x28, 0x0b,
	0x32, 0x10, 0x2e, 0x63, 0x6c, 0x61, 0x73, 0x73, 0x2e, 0x43, 0x6c, 0x61, 0x73, 0x73, 0x44, 0x61,
	0x74, 0x61, 0x48, 0x00, 0x52, 0x05, 0x63, 0x6c, 0x61, 0x73, 0x73, 0x12, 0x25, 0x0a, 0x05, 0x65,
	0x72, 0x72, 0x6f, 0x72, 0x18, 0x02, 0x20, 0x01, 0x28, 0x0b, 0x32, 0x0d, 0x2e, 0x73, 0x68, 0x61,
	0x72, 0x65, 0x64, 0x2e, 0x45, 0x72, 0x72, 0x6f, 0x72, 0x48, 0x00, 0x52, 0x05, 0x65, 0x72, 0x72,
	0x6f, 0x72, 0x42, 0x08, 0x0a, 0x06, 0x72, 0x65, 0x73, 0x75, 0x6c, 0x74, 0x22, 0x3e, 0x0a, 0x10,
	0x4a, 0x6f, 0x69, 0x6e, 0x43, 0x6c, 0x61, 0x73, 0x73, 0x52, 0x65, 0x71, 0x75, 0x65, 0x73, 0x74,
	0x12, 0x16, 0x0a, 0x06, 0x75, 0x73, 0x65, 0x72, 0x49, 0x64, 0x18, 0x01, 0x20, 0x01, 0x28, 0x09,
	0x52, 0x06, 0x75, 0x73, 0x65, 0x72, 0x49, 0x64, 0x12, 0x12, 0x0a, 0x04, 0x63, 0x6f, 0x64, 0x65,
	0x18, 0x02, 0x20, 0x01, 0x28, 0x09, 0x52, 0x04, 0x63, 0x6f, 0x64, 0x65, 0x22, 0x6e, 0x0a, 0x11,
	0x4a, 0x6f, 0x69, 0x6e, 0x43, 0x6c, 0x61, 0x73, 0x73, 0x52, 0x65, 0x73, 0x70, 0x6f, 0x6e, 0x73,
	0x65, 0x12, 0x28, 0x0a, 0x05, 0x63, 0x6c, 0x61, 0x73, 0x73, 0x18, 0x01, 0x20, 0x01, 0x28, 0x0b,
	0x32, 0x10, 0x2e, 0x63, 0x6c, 0x61, 0x73, 0x73, 0x2e, 0x43, 0x6c, 0x61, 0x73, 0x73, 0x44, 0x61,
	0x74, 0x61, 0x48, 0x00, 0x52, 0x05, 0x63, 0x6c, 0x61, 0x73, 0x73, 0x12, 0x25, 0x0a, 0x05, 0x65,
	0x72, 0x72, 0x6f, 0x72, 0x18, 0x02, 0x20, 0x01, 0x28, 0x0b, 0x32, 0x0d, 0x2e, 0x73, 0x68, 0x61,
	0x72, 0x65, 0x64, 0x2e, 0x45, 0x72, 0x72, 0x6f, 0x72, 0x48, 0x00, 0x52, 0x05, 0x65, 0x72, 0x72,
	0x6f, 0x72, 0x42, 0x08, 0x0a, 0x06, 0x72, 0x65, 0x73, 0x75, 0x6c, 0x74, 0x22, 0x56, 0x0a, 0x12,
	0x4c, 0x69, 0x73, 0x74, 0x43, 0x6c, 0x61, 0x73, 0x73, 0x65, 0x73, 0x52, 0x65, 0x71, 0x75, 0x65,
	0x73, 0x74, 0x12, 0x16, 0x0a, 0x06, 0x75, 0x73, 0x65, 0x72, 0x49, 0x64, 0x18, 0x01, 0x20, 0x01,
	0x28, 0x09, 0x52, 0x06, 0x75, 0x73, 0x65, 0x72, 0x49, 0x64, 0x12, 0x12, 0x0a, 0x04, 0x70, 0x61,
	0x67, 0x65, 0x18, 0x02, 0x20, 0x01, 0x28, 0x05, 0x52, 0x04, 0x70, 0x61, 0x67, 0x65, 0x12, 0x14,
	0x0a, 0x05, 0x6c, 0x69, 0x6d, 0x69, 0x74, 0x18, 0x03, 0x20, 0x01, 0x28, 0x05, 0x52, 0x05, 0x6c,
	0x69, 0x6d, 0x69, 0x74, 0x22, 0x74, 0x0a, 0x13, 0x4c, 0x69, 0x73, 0x74, 0x43, 0x6c, 0x61, 0x73,
	0x73, 0x65, 0x73, 0x52, 0x65, 0x73, 0x70, 0x6f, 0x6e, 0x73, 0x65, 0x12, 0x2c, 0x0a, 0x04, 0x64,
	0x61, 0x74, 0x61, 0x18, 0x01, 0x20, 0x01, 0x28, 0x0b, 0x32, 0x16, 0x2e, 0x63, 0x6c, 0x61, 0x73,
	0x73, 0x2e, 0x43, 0x6c, 0x61, 0x73, 0x73, 0x65, 0x73, 0x57, 0x69, 0x74, 0x68, 0x4d, 0x65, 0x74,
	0x61, 0x48, 0x00, 0x52, 0x04, 0x64, 0x61, 0x74, 0x61, 0x12, 0x25, 0x0a, 0x05, 0x65, 0x72, 0x72,
	0x6f, 0x72, 0x18, 0x02, 0x20, 0x01, 0x28, 0x0b, 0x32, 0x0d, 0x2e, 0x73, 0x68, 0x61, 0x72, 0x65,
	0x64, 0x2e, 0x45, 0x72, 0x72, 0x6f, 0x72, 0x48, 0x00, 0x52, 0x05, 0x65, 0x72, 0x72, 0x6f, 0x72,
	0x42, 0x08, 0x0a, 0x06, 0x72, 0x65, 0x73, 0x75, 0x6c, 0x74, 0x22, 0x47, 0x0a, 0x13, 0x47, 0x65,
	0x74, 0x43, 0x6c, 0x61, 0x73, 0x73, 0x43, 0x6f, 0x64, 0x65, 0x52, 0x65, 0x71, 0x75, 0x65, 0x73,
	0x74, 0x12, 0x16, 0x0a, 0x06, 0x75, 0x73, 0x65, 0x72, 0x49, 0x64, 0x18, 0x01, 0x20, 0x01, 0x28,
	0x09, 0x52, 0x06, 0x75, 0x73, 0x65, 0x72, 0x49, 0x64, 0x12, 0x18, 0x0a, 0x07, 0x63, 0x6c, 0x61,
	0x73, 0x73, 0x49, 0x64, 0x18, 0x02, 0x20, 0x01, 0x28, 0x09, 0x52, 0x07, 0x63, 0x6c, 0x61, 0x73,
	0x73, 0x49, 0x64, 0x22, 0x5d, 0x0a, 0x14, 0x47, 0x65, 0x74, 0x43, 0x6c, 0x61, 0x73, 0x73, 0x43,
	0x6f, 0x64, 0x65, 0x52, 0x65, 0x73, 0x70, 0x6f, 0x6e, 0x73, 0x65, 0x12, 0x14, 0x0a, 0x04, 0x63,
	0x6f, 0x64, 0x65, 0x18, 0x01, 0x20, 0x01, 0x28, 0x09, 0x48, 0x00, 0x52, 0x04, 0x63, 0x6f, 0x64,
	0x65, 0x12, 0x25, 0x0a, 0x05, 0x65, 0x72, 0x72, 0x6f, 0x72, 0x18, 0x02, 0x20, 0x01, 0x28, 0x0b,
	0x32, 0x0d, 0x2e, 0x73, 0x68, 0x61, 0x72, 0x65, 0x64, 0x2e, 0x45, 0x72, 0x72, 0x6f, 0x72, 0x48,
	0x00, 0x52, 0x05, 0x65, 0x72, 0x72, 0x6f, 0x72, 0x42, 0x08, 0x0a, 0x06, 0x72, 0x65, 0x73, 0x75,
	0x6c, 0x74, 0x32, 0xa3, 0x02, 0x0a, 0x0c, 0x43, 0x6c, 0x61, 0x73, 0x73, 0x53, 0x65, 0x72, 0x76,
	0x69, 0x63, 0x65, 0x12, 0x44, 0x0a, 0x0b, 0x63, 0x72, 0x65, 0x61, 0x74, 0x65, 0x43, 0x6c, 0x61,
	0x73, 0x73, 0x12, 0x19, 0x2e, 0x63, 0x6c, 0x61, 0x73, 0x73, 0x2e, 0x43, 0x72, 0x65, 0x61, 0x74,
	0x65, 0x43, 0x6c, 0x61, 0x73, 0x73, 0x52, 0x65, 0x71, 0x75, 0x65, 0x73, 0x74, 0x1a, 0x1a, 0x2e,
	0x63, 0x6c, 0x61, 0x73, 0x73, 0x2e, 0x43, 0x72, 0x65, 0x61, 0x74, 0x65, 0x43, 0x6c, 0x61, 0x73,
	0x73, 0x52, 0x65, 0x73, 0x70, 0x6f, 0x6e, 0x73, 0x65, 0x12, 0x3e, 0x0a, 0x09, 0x6a, 0x6f, 0x69,
	0x6e, 0x43, 0x6c, 0x61, 0x73, 0x73, 0x12, 0x17, 0x2e, 0x63, 0x6c, 0x61, 0x73, 0x73, 0x2e, 0x4a,
	0x6f, 0x69, 0x6e, 0x43, 0x6c, 0x61, 0x73, 0x73, 0x52, 0x65, 0x71, 0x75, 0x65, 0x73, 0x74, 0x1a,
	0x18, 0x2e, 0x63, 0x6c, 0x61, 0x73, 0x73, 0x2e, 0x4a, 0x6f, 0x69, 0x6e, 0x43, 0x6c, 0x61, 0x73,
	0x73, 0x52, 0x65, 0x73, 0x70, 0x6f, 0x6e, 0x73, 0x65, 0x12, 0x44, 0x0a, 0x0b, 0x6c, 0x69, 0x73,
	0x74, 0x43, 0x6c, 0x61, 0x73, 0x73, 0x65, 0x73, 0x12, 0x19, 0x2e, 0x63, 0x6c, 0x61, 0x73, 0x73,
	0x2e, 0x4c, 0x69, 0x73, 0x74, 0x43, 0x6c, 0x61, 0x73, 0x73, 0x65, 0x73, 0x52, 0x65, 0x71, 0x75,
	0x65, 0x73, 0x74, 0x1a, 0x1a, 0x2e, 0x63, 0x6c, 0x61, 0x73, 0x73, 0x2e, 0x4c, 0x69, 0x73, 0x74,
	0x43, 0x6c, 0x61, 0x73, 0x73, 0x65, 0x73, 0x52, 0x65, 0x73, 0x70, 0x6f, 0x6e, 0x73, 0x65, 0x12,
	0x47, 0x0a, 0x0c, 0x67, 0x65, 0x74, 0x43, 0x6c, 0x61, 0x73, 0x73, 0x43, 0x6f, 0x64, 0x65, 0x12,
	0x1a, 0x2e, 0x63, 0x6c, 0x61, 0x73, 0x73, 0x2e, 0x47, 0x65, 0x74, 0x43, 0x6c, 0x61, 0x73, 0x73,
	0x43, 0x6f, 0x64, 0x65, 0x52, 0x65, 0x71, 0x75, 0x65, 0x73, 0x74, 0x1a, 0x1b, 0x2e, 0x63, 0x6c,
	0x61, 0x73, 0x73, 0x2e, 0x47, 0x65, 0x74, 0x43, 0x6c, 0x61, 0x73, 0x73, 0x43, 0x6f, 0x64, 0x65,
	0x52, 0x65, 0x73, 0x70, 0x6f, 0x6e, 0x73, 0x65, 0x42, 0x11, 0x5a, 0x0f, 0x70, 0x6b, 0x67, 0x2f,
	0x70, 0x72, 0x6f, 0x74, 0x6f, 0x3b, 0x70, 0x72, 0x6f, 0x74, 0x6f, 0x62, 0x06, 0x70, 0x72, 0x6f,
	0x74, 0x6f, 0x33,
}

var (
	file_class_proto_rawDescOnce sync.Once
	file_class_proto_rawDescData = file_class_proto_rawDesc
)

func file_class_proto_rawDescGZIP() []byte {
	file_class_proto_rawDescOnce.Do(func() {
		file_class_proto_rawDescData = protoimpl.X.CompressGZIP(file_class_proto_rawDescData)
	})
	return file_class_proto_rawDescData
}

var file_class_proto_msgTypes = make([]protoimpl.MessageInfo, 10)
var file_class_proto_goTypes = []any{
	(*ClassData)(nil),            // 0: class.ClassData
	(*ClassesWithMeta)(nil),      // 1: class.ClassesWithMeta
	(*CreateClassRequest)(nil),   // 2: class.CreateClassRequest
	(*CreateClassResponse)(nil),  // 3: class.CreateClassResponse
	(*JoinClassRequest)(nil),     // 4: class.JoinClassRequest
	(*JoinClassResponse)(nil),    // 5: class.JoinClassResponse
	(*ListClassesRequest)(nil),   // 6: class.ListClassesRequest
	(*ListClassesResponse)(nil),  // 7: class.ListClassesResponse
	(*GetClassCodeRequest)(nil),  // 8: class.GetClassCodeRequest
	(*GetClassCodeResponse)(nil), // 9: class.GetClassCodeResponse
	(*Meta)(nil),                 // 10: shared.Meta
	(*Error)(nil),                // 11: shared.Error
}
var file_class_proto_depIdxs = []int32{
	0,  // 0: class.ClassesWithMeta.classes:type_name -> class.ClassData
	10, // 1: class.ClassesWithMeta.meta:type_name -> shared.Meta
	0,  // 2: class.CreateClassResponse.class:type_name -> class.ClassData
	11, // 3: class.CreateClassResponse.error:type_name -> shared.Error
	0,  // 4: class.JoinClassResponse.class:type_name -> class.ClassData
	11, // 5: class.JoinClassResponse.error:type_name -> shared.Error
	1,  // 6: class.ListClassesResponse.data:type_name -> class.ClassesWithMeta
	11, // 7: class.ListClassesResponse.error:type_name -> shared.Error
	11, // 8: class.GetClassCodeResponse.error:type_name -> shared.Error
	2,  // 9: class.ClassService.createClass:input_type -> class.CreateClassRequest
	4,  // 10: class.ClassService.joinClass:input_type -> class.JoinClassRequest
	6,  // 11: class.ClassService.listClasses:input_type -> class.ListClassesRequest
	8,  // 12: class.ClassService.getClassCode:input_type -> class.GetClassCodeRequest
	3,  // 13: class.ClassService.createClass:output_type -> class.CreateClassResponse
	5,  // 14: class.ClassService.joinClass:output_type -> class.JoinClassResponse
	7,  // 15: class.ClassService.listClasses:output_type -> class.ListClassesResponse
	9,  // 16: class.ClassService.getClassCode:output_type -> class.GetClassCodeResponse
	13, // [13:17] is the sub-list for method output_type
	9,  // [9:13] is the sub-list for method input_type
	9,  // [9:9] is the sub-list for extension type_name
	9,  // [9:9] is the sub-list for extension extendee
	0,  // [0:9] is the sub-list for field type_name
}

func init() { file_class_proto_init() }
func file_class_proto_init() {
	if File_class_proto != nil {
		return
	}
	file_shared_proto_init()
	file_class_proto_msgTypes[3].OneofWrappers = []any{
		(*CreateClassResponse_Class)(nil),
		(*CreateClassResponse_Error)(nil),
	}
	file_class_proto_msgTypes[5].OneofWrappers = []any{
		(*JoinClassResponse_Class)(nil),
		(*JoinClassResponse_Error)(nil),
	}
	file_class_proto_msgTypes[7].OneofWrappers = []any{
		(*ListClassesResponse_Data)(nil),
		(*ListClassesResponse_Error)(nil),
	}
	file_class_proto_msgTypes[9].OneofWrappers = []any{
		(*GetClassCodeResponse_Code)(nil),
		(*GetClassCodeResponse_Error)(nil),
	}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: file_class_proto_rawDesc,
			NumEnums:      0,
			NumMessages:   10,
			NumExtensions: 0,
			NumServices:   1,
		},
		GoTypes:           file_class_proto_goTypes,
		DependencyIndexes: file_class_proto_depIdxs,
		MessageInfos:      file_class_proto_msgTypes,
	}.Build()
	File_class_proto = out.File
	file_class_proto_rawDesc = nil
	file_class_proto_goTypes = nil
	file_class_proto_depIdxs = nil
}
